# Generated by Django 5.0 on 2024-01-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
