# Generated by Django 5.0 on 2024-01-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(default='Sugerencia del Chef', max_length=80),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.FloatField(),
        ),
    ]
