# Generated by Django 5.0 on 2024-01-05 20:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_plato_categoria_alter_plato_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('categoria', models.CharField(default='Sugerencia del Chef', max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='descripcion',
            new_name='historia',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.AddField(
            model_name='plato',
            name='tiempo_elaboracion',
            field=models.TimeField(default=datetime.time(0, 30)),
        ),
        migrations.AddField(
            model_name='plato',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='platos.subcategoria'),
        ),
    ]
