# Generated by Django 5.0 on 2024-01-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_subcategoria_rename_descripcion_plato_historia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='disponible',
            field=models.CharField(default='on'),
        ),
    ]
