# Generated by Django 5.0 on 2024-01-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_alter_plato_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='disponible',
            field=models.CharField(default='off'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.CharField(default='Especial', max_length=80),
        ),
    ]
