# Generated by Django 5.0 on 2024-01-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0005_alter_plato_disponible_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
