# Generated by Django 5.0 on 2024-01-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0006_alter_plato_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
